development:
  clients:
    default:
      database: test_orm_mongoid
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: test_orm_mongoid_test
      hosts:
        - localhost:27017
